<?php

/**
 * Canonical frontend route permissions (null = any authenticated user, read-open).
 * Keep in sync with panel/frontend/src/lib/routePermissions.ts
 */
return [
    '/hosting/plans' => 'hosting.manage',
    '/hosting/accounts' => 'hosting.manage',
    '/users' => 'users.manage',
    '/security/2fa' => null,
    '/security/risks' => 'security.manage',
    '/security/firewall' => 'security.manage',
    '/security/waf' => 'security.manage',
    '/security/tamper' => 'security.manage',
    '/security/fail2ban' => 'security.manage',
    '/security/sshkeys' => 'security.manage',
    '/security/clamav' => 'security.manage',
    '/security/audit' => 'security.manage',
    '/system/disk' => 'system.manage',
    '/websites' => null,
    '/domains' => null,
    '/subdomains' => null,
    '/databases' => null,
    '/webserver/vhosts' => 'system.manage',
    '/apps' => 'apps.manage',
    '/softstore' => null,
    '/runtimes' => null,
    '/monitoring/services' => 'monitoring.manage',
    '/monitoring/processes' => 'monitoring.manage',
    '/monitoring/logs' => 'monitoring.manage',
    '/monitoring/uptime' => 'monitoring.manage',
    '/monitoring/channels' => 'monitoring.manage',
    '/api-tokens' => 'tokens.manage',
    '/webhooks' => 'webhooks.manage',
    '/profile' => null,
    '/settings' => null,
    '/forbidden' => null,
    '/dns' => null,
    '/ssl' => null,
    '/ftp' => null,
    '/phpmyadmin' => 'embed.phpmyadmin',
    '/phppgadmin' => 'embed.phppgadmin',
    '/php-settings' => null,
    '/email/domains' => null,
    '/email/auth' => null,
    '/email/accounts' => null,
    '/email/forwarders' => null,
    '/email/autoresponders' => null,
    '/email/lists' => null,
    '/email/queue' => 'system.manage',
    '/email/antispam' => null,
    '/webmail' => 'embed.webmail',
    '/files' => 'system.manage',
    '/terminal' => 'system.manage',
    '/cron' => 'system.manage',
    '/backups' => null,
    '/system-info' => null,
    '/metrics-alerts' => null,
    '/sites' => null,
    '/products' => null,
    '/git' => null,
    '/wordpress' => null,
    '/support' => null,
];
